### ISSUE TITLE
how do I install it?

### ISSUE THREAD

**Issue by ducklin5** [mamatheking/CrapSnap#1]
Do i just download the jad/jar file and open it in my blackberry or is there something else i must do?

**Comment by PropheteMath** [comment]
Hi !
There is many ways to install the app. The two I personnaly use : 

-You can compile it and deploy it trough Eclipse (with BlackBerry SDK configured).
-You can install by using Blackberry Desktop Software (You will need the .cod & the .alx file it the same directory)
Here a video which show you how to : https://www.youtube.com/watch?v=mmt735G1oo0

Of course there is a way to do it directly from the phone, but I don't remember : I use it only once. Don't hesitate to google ;)

**Comment by ducklin5** [comment]
I did some research and i found that it is banned and i will most probably be kicked off the server then banned. Is this true?

**Comment by PropheteMath** [comment]
I did some research and i found that it is banned and i will most probably be kicked off the server then banned. Is this true?

**Comment by devnoname120** [comment]
@ducklin5 In order to install this, you can transfer [this folder](https://github.com/mamatheking/CrapSnap/tree/master/deliverables/Web/7.1.0) to your Blackberry and open CrapSnap.jad in the web browser.
